update workflow

diff --git a/.github/workflows/librarian.yaml b/.github/workflows/librarian.yaml
--- a/.github/workflows/librarian.yaml
+++ b/.github/workflows/librarian.yaml
@@ -12,15 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 name: Librarian
-on:
-  push:
-  pull_request:
-    types:
-      - opened
-      - reopened
-      - synchronize
-      - closed
-  merge_group:
+on: [push, pull_request, merge_group]
 permissions:
   contents: read
   issues: write
@@ -41,16 +33,10 @@ jobs:
           cd /usr/local
           sudo unzip -x /tmp/protoc.zip
           protoc --version
-          go install github.com/google/yamlfmt/cmd/yamlfmt@v0.17.2
           go install golang.org/x/tools/cmd/goimports@latest
       - name: Run tests
         id: run-tests
         run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
-        continue-on-error: true
-      - name: Check YAML formatting
-        id: check-yaml
-        run: |
-          yamlfmt .
         continue-on-error: true
       - name: Detect formatting changes
         run: git diff --exit-code
@@ -59,14 +45,19 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
       - name: Create an issue for push event
-        if: "github.event.pull_request.merged == true && github.ref == 'refs/heads/main' && (steps.run-tests.outcome == 'failure' || steps.check-yaml.outcome == 'failure')"
+        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.run-tests.outcome == 'failure' }}
         run: |
           ISSUE_TITLE="all: tests failed at HEAD"
           BODY="Tests failed at HEAD of the \`main\` branch. Please review Workflow Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for detail."
-          gh issue create --title "$ISSUE_TITLE" --body "$BODY" --label "critical" -R $GH_REPO
+          gh issue create --title "$ISSUE_TITLE" --body "$BODY" --label ":rotating_light: critical" -R $GH_REPO
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
+      - name: Check unit tests result
+        if: ${{ steps.run-tests.outcome == 'failure' }}
+        run: |
+          echo "Unit tests failed"
+          exit 1
   e2e-test:
     runs-on: ubuntu-24.04
     steps:
